edge_publish:
    stage: build
    environment:
        name: edge
    tags:
        - krispii
    only:
        - edge
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
            - target/

stage_publish:
    stage: build
    environment:
        name: staging
    tags:
        - krispii
    only:
        - staging
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
            - target/

live_publish:
    stage: build
    environment:
        name: master
    tags:
        - krispii
    only:
        - master
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
            - target/

