ci_compile:
    stage: build
    only:
        - edge
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=edge https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
        - target/

#publish_local:
#    stage: deploy
#    only:
#        - edge
#    script:
#        - sbt publishLocal
#        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=edge https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"