edge_publish:
    stage: build
    environment:
        name: edge
    tags:
        - krispii
    only:
        - edge
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
    cache:
        paths:
            - target/

#publish_local:
#    stage: deploy
#    environment:
#        name: edge
#    only:
#        - edge
#    script:
#        - sbt publishLocal

oms_publish:
    stage: build
    environment:
        name: oms
    tags:
        - krispii
    only:
        - exam-team
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
    cache:
        paths:
            - target/

stage_publish:
    stage: build
    environment:
        name: staging
    tags:
        - krispii
    only:
        - staging
        - master
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
    cache:
        paths:
            - target/
