edge_compile:
    stage: build
    environment:
        name: edge
    tags:
        - krispii
    only:
        - edge
        - staging
        - master
        - oms-dev
        ## - pipeline-testing
        ## - classroom_debugging
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
        - target/

#publish_local:
#    stage: deploy
#    environment:
#        name: edge
#    only:
#        - edge
#    script:
#        - sbt publishLocal
#        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"

oms_compile:
    stage: build
    environment:
        name: oms
    tags:
        - krispii
    only:
        - oms-dev
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
            - target/

stage_compile:
    stage: build
    environment:
        name: staging
    tags:
        - krispii
    only:
        - staging
        - master
    script:
        - sbt -Dsbt.log.noformat=true clean compile compile:doc publishLocal
        - "curl --request POST --form token=0ab10ae8c48c27f1270f5c1c8332fa --form ref=$CI_COMMIT_REF_NAME https://gitlab.shiftfocus.ca/api/v4/projects/28/trigger/pipeline"
    cache:
        paths:
            - target/
