DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS users_roles CASCADE;
DROP TABLE IF EXISTS classes CASCADE;
DROP TABLE IF EXISTS users_classes CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS schedule_exceptions CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS parts CASCADE;
DROP TABLE IF EXISTS documents CASCADE;
DROP TABLE IF EXISTS document_revisions CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS long_answer_tasks CASCADE;
DROP TABLE IF EXISTS short_answer_tasks CASCADE;
DROP TABLE IF EXISTS multiple_choice_tasks CASCADE;
DROP TABLE IF EXISTS ordering_tasks CASCADE;
DROP TABLE IF EXISTS matching_tasks CASCADE;
DROP TABLE IF EXISTS task_feedbacks CASCADE;
DROP TABLE IF EXISTS task_notes CASCADE;
DROP TABLE IF EXISTS components CASCADE;
DROP TABLE IF EXISTS audio_components CASCADE;
DROP TABLE IF EXISTS text_components CASCADE;
DROP TABLE IF EXISTS video_components CASCADE;
DROP TABLE IF EXISTS component_notes CASCADE;
DROP TABLE IF EXISTS work CASCADE;
DROP TABLE IF EXISTS long_answer_work CASCADE;
DROP TABLE IF EXISTS short_answer_work CASCADE;
DROP TABLE IF EXISTS multiple_choice_work CASCADE;
DROP TABLE IF EXISTS ordering_work CASCADE;
DROP TABLE IF EXISTS matching_work CASCADE;

/*
DROP TABLE IF EXISTS class_schedule_exceptions CASCADE;
DROP TABLE IF EXISTS logbook CASCADE;
DROP TABLE IF EXISTS class_schedules CASCADE;
DROP TABLE IF EXISTS student_responses CASCADE;
DROP TABLE IF EXISTS scheduled_classes_parts CASCADE;
DROP TABLE IF EXISTS classes_projects CASCADE;

DROP TABLE IF EXISTS activity_log CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS components_parts CASCADE;
DROP TABLE IF EXISTS project_templates CASCADE;
*/